name: focus_flow
description: Stay in Flow, Build Deep Work Habits
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  permission_handler: ^11.3.1
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  
  # Data Classes
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Navigation
  go_router: ^14.2.0
  
  # UI Components
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0
  glass_kit: ^3.0.0
  
  # Notifications
  flutter_local_notifications: ^17.2.1
  
  # Audio
  just_audio: ^0.9.39
  audio_session: ^0.1.21
  
  # Localization
  intl: ^0.20.2
  
  # Utilities
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  home_widget: ^0.6.0
  vibration: ^1.9.0
  
  # Icons & Assets
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  
flutter:
  uses-material-design: true

    
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700